#!/usr/bin/env python3
"""Generates driver/version.h and driver/Show2Cam.inf.

Show2Cam is one root-enumerated device (ROOT\\Show2Cam) with up to MAX_CAMERAS cameras. Each camera is an AVStream
filter whose device interfaces (video, capture, video camera) carry the reference string "Camera<N>"; the INF gives
each of them a friendly name, "Show2Cam Camera <N>" by default (the Show2Cam program can rename them).
"""
import os
import datetime

MAX_CAMERAS = 10
MIN_OS = '10.0...19041'         # TargetOSVersion decoration of the INF models sections (Windows 10 2004+)
AUTHOR = 'Symo'                 # author / developer: version resources, INF provider, installer, README
EMAIL = 'symops@gmail.com'

HERE = os.path.dirname(os.path.abspath(__file__))

# Every build gets a new version: Windows identifies a driver package by its INF, and an INF with an unchanged
# DriverVer is treated as "already imported".
NOW = datetime.datetime.now()
VERSION = (1, 0, NOW.timetuple().tm_yday, NOW.hour * 60 + NOW.minute)   # 1.0.<day of year>.<minute of day>
VERSION_STR = '.'.join(map(str, VERSION))
DRIVER_DATE = NOW.strftime('%m/%d/%Y')

KSCATEGORY = {
    'KSCATEGORY_CAPTURE': '{65E8773D-8F56-11D0-A3B9-00A0C9223196}',
    'KSCATEGORY_VIDEO': '{6994AD05-93EF-11D0-A3CC-00A0C9223196}',
    'KSCATEGORY_VIDEO_CAMERA': '{E5323777-F976-4F5B-9B55-B94699C46E44}',
}


def camera_name(i):
    return f'Show2Cam Camera {i}'


def gen_version():
    lines = ['// Generated by gen.py at build time - do not edit.', '#pragma once',
             f'#define S2C_VER_MAJOR {VERSION[0]}', f'#define S2C_VER_MINOR {VERSION[1]}',
             f'#define S2C_VER_BUILD {VERSION[2]}', f'#define S2C_VER_REV   {VERSION[3]}',
             f'#define S2C_VER_STR   "{VERSION_STR}"',
             f'#define S2C_AUTHOR    "{AUTHOR}"', f'#define S2C_EMAIL     "{EMAIL}"',
             f'#define S2C_COPYRIGHT "Copyright (C) {NOW.year} {AUTHOR} <{EMAIL}>"',
             f'#define S2C_MAX_CAMERAS_INF {MAX_CAMERAS}', '']
    open(os.path.join(HERE, 'driver', 'version.h'), 'w', newline='\r\n').write('\n'.join(lines))


def gen_inf():
    out = []
    a = out.append
    a('; Show2Cam.inf - generated by gen.py, do not edit by hand.')
    a('; Virtual cameras "Show2Cam Camera 1".."%d" (AVStream).' % MAX_CAMERAS)
    a('')
    a('[Version]')
    a('Signature="$WINDOWS NT$"')
    a('Class=Camera')
    a('ClassGuid={ca3e7ab9-b4c3-4ae6-8251-579ef933890f}')
    a('Provider=%ProviderName%')
    a(f'DriverVer={DRIVER_DATE},{VERSION_STR}')
    a('CatalogFile=Show2Cam.cat')
    a('PnpLockdown=1')
    a('')
    a('[SourceDisksNames]')
    a('1=%DiskName%,,,')
    a('')
    a('[SourceDisksFiles]')
    a('Show2Cam.sys=1')
    a('')
    a('[DestinationDirs]')
    a('DefaultDestDir=13')
    a('')
    a('[Manufacturer]')
    a(f'%MfgName%=Show2Cam,NTamd64.{MIN_OS},NTarm64.{MIN_OS}')
    a('')
    for arch in ('NTamd64', 'NTarm64'):
        a(f'[Show2Cam.{arch}.{MIN_OS}]')
        a('%DeviceDesc%=Show2Cam_Device,ROOT\\Show2Cam')
        a('')
    a('[Show2Cam_Device.NT]')
    a('Include=ks.inf,kscaptur.inf')
    a('Needs=KS.Registration,KSCAPTUR.Registration.NT')
    a('CopyFiles=Show2Cam.CopyFiles')
    a('')
    a('[Show2Cam.CopyFiles]')
    a('Show2Cam.sys')
    a('')
    a('[Show2Cam_Device.NT.Interfaces]')
    for i in range(1, MAX_CAMERAS + 1):
        for cat in KSCATEGORY:
            a(f'AddInterface=%{cat}%,"Camera{i}",Show2Cam.Camera{i}')
    a('')
    for i in range(1, MAX_CAMERAS + 1):
        a(f'[Show2Cam.Camera{i}]')
        a(f'AddReg=Show2Cam.Camera{i}.AddReg')
        a(f'[Show2Cam.Camera{i}.AddReg]')
        a('HKR,,CLSID,,%Proxy.CLSID%')
        a(f'HKR,,FriendlyName,,%Camera{i}%')
        a('')
    a('[Show2Cam_Device.NT.Services]')
    a('AddService=Show2Cam,0x00000002,Show2Cam_Service')
    a('')
    a('[Show2Cam_Service]')
    a('DisplayName=%SvcDesc%')
    a('ServiceType=1')
    a('StartType=3')
    a('ErrorControl=1')
    a('ServiceBinary=%13%\\Show2Cam.sys')
    a('AddReg=Show2Cam.Params.AddReg')
    a('')
    a('; Defaults; 0x00010003 = REG_DWORD, do not overwrite values changed by the user.')
    a('[Show2Cam.Params.AddReg]')
    a('HKR,Parameters,CameraCount,0x00010003,1')
    a('')
    a('[Strings]')
    a(f'ProviderName="{AUTHOR}"')
    a(f'MfgName="{AUTHOR}"')
    a('DeviceDesc="Show2Cam"')
    a('SvcDesc="Show2Cam driver"')
    a('DiskName="Show2Cam disk"')
    a('Proxy.CLSID="{17CCA71B-ECD7-11D0-B908-00A0C9223196}"')
    for cat, guid in KSCATEGORY.items():
        a(f'{cat}="{guid}"')
    for i in range(1, MAX_CAMERAS + 1):
        a(f'Camera{i}="{camera_name(i)}"')
    open(os.path.join(HERE, 'driver', 'Show2Cam.inf'), 'w', newline='\r\n').write('\n'.join(out) + '\n')


if __name__ == '__main__':
    gen_version()
    gen_inf()
    print(f'driver/version.h and driver/Show2Cam.inf generated (version {VERSION_STR})')
